# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LidarCampania
                                 A QGIS plugin
 importazione dati lidar Campania
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-29
        copyright            : (C) 2021 by Enzo Cocca
        email                : enzo.ccc@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LidarCampania class from file LidarCampania.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lidar_campania import LidarCampania
    return LidarCampania(iface)
